[channel-slider] Show the spin buttons all the time
color-js/elements pull request #168
Opened 2024-11-20 18:03 UTC by DmitrySharabin

But make them subtly until the user interacts with them.

<img width="982" alt="image" src="https://github.com/user-attachments/assets/aec025c3-9e23-47cb-9801-7f06fb896106">

<img width="983" alt="image" src="https://github.com/user-attachments/assets/6568e6d5-97cf-4f55-ac7a-32dfeeb678b7">

Unfortunately, we are a bit tight with options here (except lowering `opacity` or applying filters, as far as I'm aware). But from my perspective, filters are a bit too much in this case.

2024-11-20 18:07 UTC, LeaVerou requested changes
Can we also make the spin buttons have a transparent bg when not interacted with?

2024-11-20 18:08 UTC, DmitrySharabin commented
> Can we also make the spin buttons have a transparent bg when not interacted with?

I tried it. No luck.

2024-11-20 20:53 UTC, DmitrySharabin commented
OK, the result with `filter: contrast(2)` looks closer to the desired one. Thank you for the hint!

2024-11-21 21:07 UTC, LeaVerou approved these changes

2024-11-22 11:18 UTC, merged