[color-picker] Add support for `alpha`, closes #57
color-js/elements pull request #174
Opened 2024-11-27 17:03 UTC by DmitrySharabin

Related to #173 (and should be merged after it). Works with all versions of Color.js

2024-11-27 17:57 UTC, DmitrySharabin commented
Now, when #173 is merged, we can support alpha and in `<color-picker>`, too.

2024-12-04 07:15 UTC, LeaVerou requested changes
What are the use cases for showing the alpha only some of the time? I think this can be quite jarring when people are typing. Unless it is driven by actual user requests I suggest we go with a simple boolean alpha for now.

2024-12-04 11:12 UTC, DmitrySharabin commented
> What are the use cases for showing the alpha only some of the time? I think this can be quite jarring when people are typing. Unless it is driven by actual user requests I suggest we go with a simple boolean alpha for now.

I have no objections. Done!

2024-12-05 18:13 UTC, LeaVerou approved these changes

2024-12-05 19:04 UTC, merged