[color-gamut] Add reference tables to docs
color-js/elements pull request #40
Opened 2024-05-16 15:34 UTC by DmitrySharabin

- attributes & properties
- events
- CSS variables

2024-05-16 15:42 UTC, LeaVerou commented on src/color-gamut/README.md
> +| `--gamut-color` | `<color>` | Background color of gamut indicator. |
```suggestion
| `--gamut-color` | `<color>` | Background color of gamut indicator. Will override the color that depends on the actual gamut, so you should rarely use this directly. |
```

And move it to the end.

2024-05-16 15:46 UTC, LeaVerou requested changes
See comments

2024-05-16 15:51 UTC, DmitrySharabin commented on src/color-gamut/README.md
> +| `--color-neutral-60` | `<color>` | Neutral background color of gamut indicator. |
Done

2024-05-16 15:59 UTC, DmitrySharabin commented on src/color-gamut/README.md
> +| `--color-red-dark` | `<color>` | Dark red background color of gamut indicator. |
Done

2024-05-16 16:00 UTC, DmitrySharabin commented on src/color-gamut/README.md
> +| `gamuts` | `gamuts` | `string` &#124; `Array<string>` &#124; `object` | `["srgb", "p3", "rec2020", "prophoto"]` | A list of gamuts to use. |
Agreed that we don't have enough info here.

2024-05-17 13:57 UTC, LeaVerou approved these changes

2024-05-17 13:57 UTC, merged

2024-05-17 13:58 UTC, LeaVerou commented on src/color-gamut/README.md
> -| `--color-neutral-60` | `<color>` | Neutral background color of gamut indicator. |
Gah, I didn’t mean remove this, I meant there needs to be a better variable here. I’m on it, keep an eye out so you can review.